version: '3'
services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        command: yarn run dev
        ports:
            - 3001:3001
        volumes:
            - ./src:/usr/src/app/src:z